// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Configuration")>]
[<assembly: AssemblyProductAttribute("FSharp.Configuration")>]
[<assembly: AssemblyDescriptionAttribute("The FSharp.Configuration project contains type providers for the configuration of .NET projects.")>]
[<assembly: AssemblyVersionAttribute("0.6.4")>]
[<assembly: AssemblyFileVersionAttribute("0.6.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Configuration"
    let [<Literal>] AssemblyProduct = "FSharp.Configuration"
    let [<Literal>] AssemblyDescription = "The FSharp.Configuration project contains type providers for the configuration of .NET projects."
    let [<Literal>] AssemblyVersion = "0.6.4"
    let [<Literal>] AssemblyFileVersion = "0.6.4"
