// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Configuration")>]
[<assembly: AssemblyProductAttribute("FSharp.Configuration")>]
[<assembly: AssemblyDescriptionAttribute("The FSharp.Configuration project contains type providers for the configuration of .NET projects.")>]
[<assembly: AssemblyVersionAttribute("1.4.0")>]
[<assembly: AssemblyFileVersionAttribute("1.4.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Configuration"
    let [<Literal>] AssemblyProduct = "FSharp.Configuration"
    let [<Literal>] AssemblyDescription = "The FSharp.Configuration project contains type providers for the configuration of .NET projects."
    let [<Literal>] AssemblyVersion = "1.4.0"
    let [<Literal>] AssemblyFileVersion = "1.4.0"
